replicaCount: 1

image:
  repository: grafana/grafana
  tag: latest

service:
  port: 3000
  targetPort: 3000

resources:
  limits:
    memory: "1Gi"
    cpu: "1000m"
  requests:
    memory: "500Mi"
    cpu: "500m"

grafana:
  dataSource:
    url: "http://prometheus-service.svc.cluster.local:9090"
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

