apiVersion: batch/v1
kind: Job
metadata:
  name: neo4j-constraints-job
spec:
  template:
    spec:
      volumes:
        - name: constraints-volume
          configMap:
            name: neo4j-constraints-config
      containers:
        - name: neo4j-constraints
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          volumeMounts:
            - name: constraints-volume
              mountPath: /import
          env:
            - name: NEO4J_USERNAME
              value: {{ .Values.job.NEO4J_USERNAME }}
            - name: NEO4J_PASSWORD
              value: {{ .Values.job.NEO4J_PASSWORD }}
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo 'Creating constraints and indexes ...'
              until cypher-shell -u $NEO4J_USERNAME -p $NEO4J_PASSWORD -a bolt://neo4j-deployment-svc:7687 "RETURN 'Neo4j is up'"; do
                echo 'Waiting for Neo4j to be ready...'
                sleep 5
              done
              cypher-shell -u $NEO4J_USERNAME -p $NEO4J_PASSWORD -a bolt://neo4j-deployment-svc:7687 --file /import/v2_entity_constraints.cql
              echo 'Constraints and indexes are created ✅'
      restartPolicy: OnFailure
