apiVersion: v1
kind: Secret
metadata:
  name: neo4j-secret
type: Opaque
data:
  NEO4J_AUTH: {{ .Values.neo4jSecret.NEO4J_AUTH }}
  NEO4J_USERNAME: {{ .Values.neo4jSecret.NEO4J_USERNAME }}
  NEO4J_PASSWORD: {{ .Values.neo4jSecret.NEO4J_PASSWORD }}