apiVersion: v1
kind: Service
metadata:
  name: neo4j-external
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: neo4j
  ports:
  - protocol: TCP
    port: 7687
    targetPort: 7687