apiVersion: v1
kind: Service
metadata:
  name: neo4j-svc
  annotations:
    cloud.google.com/backend-config: '{"ports": { "{{ .Values.service.httpsPort | quote }}": "neo4j-backendconfig" }}'
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: 7474
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: 7473
    - name: bolt
      port: {{ .Values.service.boltPort }}
      targetPort: 7687
  selector:
    app: neo4j