apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-config
data:
  v2_entity_constraints.cql: |-
    {{ .Files.Get "files/v2_entity_constraints.cql" | nindent 8 }}
  f_neodash.json: |-
    {{ .Files.Get "files/f_neodash.json" | nindent 8 }}
  pt_neodash.json: |-
    {{ .Files.Get "files/pt_neodash.json" | nindent 8 }}