version: "3.8"

##############################################################################
#
# services
# - pipelayer
#
##############################################################################
services:

  ####################
  # pipelayer
  ####################
  pipelayer:
    build: pipelayer
    container_name: pipelayer
    networks:
      - backend
    ports:
      - 8080:80
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://pipelayer"]
      interval: 60s
      timeout: 10s
      retries: 20

################################################################################
#
# networks
# - backend
#
################################################################################
networks:
  backend:
    name: backend
    external: true
