version: "3.8"

##############################################################################
#
# services
# - text-classifier
#
##############################################################################
services:

  ####################
  # text-classifier
  ####################
  text-classifier:
    image: text-classifier:latest
    container_name: text-classifier
    build:
      context: ./
      dockerfile: conf/nlp/text-classifier/Dockerfile
    networks:
      - backend
    environment:
      - HF_DATASETS_CACHE=/cache/datasets
      - TRANSFORMERS_CACHE=/cache/transformers
    volumes:
      - $PWD/cache/nlp/text-classifier/datasets:/cache/datasets
      - $PWD/cache/nlp/text-classifier/transformers:/cache/transformers

  ####################
  # question-answer
  ####################
  question-answer:
    image: question-answer:latest
    container_name: question-answer
    build:
      context: ./
      dockerfile: conf/nlp/question-answer/Dockerfile
    networks:
      - backend
    environment:
      - HF_DATASETS_CACHE=/cache/datasets
      - TRANSFORMERS_CACHE=/cache/transformers
    volumes:
      - $PWD/cache/nlp/question-answer/datasets:/cache/datasets
      - $PWD/cache/nlp/question-answer/transformers:/cache/transformers

  ####################
  # summarizer
  ####################
  summarizer:
    image: summarizer:latest
    container_name: summarizer
    build:
      context: ./
      dockerfile: conf/nlp/summarizer/Dockerfile
    networks:
      - backend
    environment:
      - HF_DATASETS_CACHE=/cache/datasets
      - TRANSFORMERS_CACHE=/cache/transformers
    volumes:
      - $PWD/cache/nlp/summarizer/datasets:/cache/datasets
      - $PWD/cache/nlp/summarizer/transformers:/cache/transformers

################################################################################
#
# networks
# - backend
#
################################################################################
networks:
  backend:
    name: backend
    # external: true
