apiVersion: v1
kind: Service
metadata:
  name: governance-ui-svc
  namespace: "bc"
spec:
  ports:
    - port: 3000
      targetPort: 3000      
      protocol: TCP
      name: http-ui
  selector:
    app: governance-ui
---
apiVersion: v1
kind: Service
metadata:
  name: governance-wss
  namespace: "bc"
spec:
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: tcp-wss 
  selector:
    app: governance-ui