## ------------------------------------------------------
## Zookeeper
## ------------------------------------------------------
cp-zookeeper:
  servers: 3

## ------------------------------------------------------
## Kafka UI
## ------------------------------------------------------
cp-kafka-ui:
  paradire:
    pt: "ab"

## ------------------------------------------------------
## Kafka Job
## ------------------------------------------------------
cp-kafka-job:
  samplingSize: 5
  pt: "ab"
  GCPBucketName: "paradire-synthea-data"


## ------------------------------------------------------
## Governance UI
## ------------------------------------------------------
governance-ui:
  pt: "ab"
