## ------------------------------------------------------
## acg
## ------------------------------------------------------
acg:
  enabled: true
  pt: "ab"

## ------------------------------------------------------
## Kafka
## ------------------------------------------------------
cp-kafka:
  enabled: true
  persistence:
    size: 20Gi

## ------------------------------------------------------
## Kafka CJ
## ------------------------------------------------------
cp-kafka-cj:
  enabled: true
  samplingSize: 500
  pt: "ab"
  cronJob: "true"
  GCPBucketName: "paradire-synthea-data"
  cronSchedule: "0 0 * * *"

## ------------------------------------------------------
## Kafka Connect
## ------------------------------------------------------
cp-kafka-connect:
  enabled: true
  persistence:
    size: 10Gi

## ------------------------------------------------------
## Kafka Job
## ------------------------------------------------------
cp-kafka-job:
  enabled: true
  samplingSize: 5
  pt: "ab"
  cronJob: "false"
  GCPBucketName: "paradire-synthea-data"

## ------------------------------------------------------
## REST Proxy
## ------------------------------------------------------
cp-kafka-rest:
  enabled: true

## ------------------------------------------------------
## Kafka UI
## ------------------------------------------------------
cp-kafka-ui:
  enabled: true
  kafkaUiSecret:
    username: "a2Fma2F1aQ=="  # base64 encoded 'kafkaui'
    password: "cGhhY0AyMDIz"  # base64 encoded 'phac@2023'
  paradire:
    pt: "ab"

## ------------------------------------------------------
## KSQL Server
## ------------------------------------------------------
cp-ksql-server:
  enabled: true

## ------------------------------------------------------
## Schema Registry
## ------------------------------------------------------
cp-schema-registry:
  enabled: true

## ------------------------------------------------------
## Zookeeper
## ------------------------------------------------------
cp-zookeeper:
  servers: 3
  enabled: true
  persistence:
    enabled: true
    dataDirSize: 10Gi
    dataLogDirSize: 10Gi

## ------------------------------------------------------
## Governance UI
## ------------------------------------------------------
governance-ui:
  enabled: true
  pt: "ab"

## ------------------------------------------------------
## Hapi-fhir-server
## ------------------------------------------------------
hapi-fhir-server:
  enabled: true
  db:
    size: "20Gi"
  postgresSecret:
    postgresPassword: "YWRtaW4="  # base64 encoded 'admin'
    postgresUser: "YWRtaW4="      # base64 encoded 'admin'
    postgresDB: "aGFwaQ=="        # base64 encoded 'hapi'
  paradire:
    pt: "ab"

## ------------------------------------------------------
## Neo4j
## ------------------------------------------------------
neo4j:
  enabled: true
  storage:
    dataPvcSize: "50Gi"
    importPvcSize: "50Gi"
    logsPvcSize: "50Gi"
    pluginsPvcSize: "50Gi"
  env-val: statging
  neo4jSecret:
    NEO4J_AUTH: "bmVvNGovcGhhY0AyMDIz" # base64 encoded 'neo4j/phac@2023'
    NEO4J_USERNAME: "bmVvNGo="         # base64 encoded 'neo4j'
    NEO4J_PASSWORD: "cGhhY0AyMDIz"     # base64 encoded 'phac@2023'
    
## ------------------------------------------------------
## Neodash
## ------------------------------------------------------
neodash:
  enabled: true

## ------------------------------------------------------
## paradire-ingress
## ------------------------------------------------------
paradire-ingress:
  enabled: true
  env: statging
  pt: "ab"

## ------------------------------------------------------
## patient-browser
## ------------------------------------------------------
patient-browser:
  enabled: true
  paradire:
    pt: "ab"

## ------------------------------------------------------
## neodash-designer
## ------------------------------------------------------
neodash-designer:
  enabled: true
  paradire:
    pt: "ab"