## ------------------------------------------------------
## acg
## ------------------------------------------------------
acg:
  enabled: true

## ------------------------------------------------------
## Kafka
## ------------------------------------------------------
cp-kafka:
  enabled: true

## ------------------------------------------------------
## Kafka CJ
## ------------------------------------------------------
cp-kafka-cj:
  enabled: true
  samplingSize: 100
  pt: "ab"
  cronJob: "true"
  GCPBucketName: "paradire-synthea-data"
  cronSchedule: "0 0 * * *"

## ------------------------------------------------------
## Kafka Connect
## ------------------------------------------------------
cp-kafka-connect:
  enabled: true

## ------------------------------------------------------
## Kafka Job
## ------------------------------------------------------
cp-kafka-job:
  enabled: true
  samplingSize: 5
  pt: "ab"
  cronJob: "false"
  GCPBucketName: "paradire-synthea-data"

## ------------------------------------------------------
## REST Proxy
## ------------------------------------------------------
cp-kafka-rest:
  enabled: true

## ------------------------------------------------------
## Kafka UI
## ------------------------------------------------------
cp-kafka-ui:
  enabled: true
  paradire:
    pt: "ab"

## ------------------------------------------------------
## KSQL Server
## ------------------------------------------------------
cp-ksql-server:
  enabled: true

## ------------------------------------------------------
## Schema Registry
## ------------------------------------------------------
cp-schema-registry:
  enabled: true

## ------------------------------------------------------
## Zookeeper
## ------------------------------------------------------
cp-zookeeper:
  servers: 3
  enabled: true

## ------------------------------------------------------
## Governance UI
## ------------------------------------------------------
governance-ui:
  enabled: true
  pt: "ab"

## ------------------------------------------------------
## Hapi-fhir-server
## ------------------------------------------------------
hapi-fhir-server:
  enabled: true

## ------------------------------------------------------
## Neo4j
## ------------------------------------------------------
neo4j:
  enabled: true

## ------------------------------------------------------
## Neodash
## ------------------------------------------------------
neodash:
  enabled: true

## ------------------------------------------------------
## paradire-ingress
## ------------------------------------------------------
paradire-ingress:
  enabled: true

## ------------------------------------------------------
## patient-browser
## ------------------------------------------------------
patient-browser:
  enabled: true

## ------------------------------------------------------
## neodash-designer
## ------------------------------------------------------
neodash-designer:
  enabled: true