apiVersion: v1
kind: Service
metadata:
  name: neodash-svc
  annotations:
    cloud.google.com/backend-config: '{"ports": { {{ .Values.service.port | quote }}: "neo4j-backendconfig" }}'
spec:
  selector:
    app: neodash
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
