apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-ksql-server.fullname" . }}
  labels:
    app: {{ template "cp-ksql-server.name" . }}
    chart: {{ template "cp-ksql-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
      - name: http-server
        port: {{ .Values.servicePort }}
    {{- if .Values.prometheus.jmx.enabled }}
      - name: tcp-metrics
        port: {{ .Values.prometheus.jmx.port }}
    {{- end }}
  selector:
    app: {{ template "cp-ksql-server.name" . }}
    release: {{ .Release.Name }}
