apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-cert
  namespace: istio-ingress
spec:
  dnsNames:
    - iidi.alpha.phac.gc.ca
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  secretName: tlskeys