apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-service-account
  namespace: "{{ .Values.pt }}"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-status-reader
  namespace: "{{ .Values.pt }}"
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-status-binding
  namespace: "{{ .Values.pt }}"
subjects:
- kind: ServiceAccount
  name: job-service-account
  namespace: "{{ .Values.pt }}"
roleRef:
  kind: Role
  name: job-status-reader
  apiGroup: rbac.authorization.k8s.io
