replicaCount: 1

image:
  repository: neo4j
  tag: "5.8.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  httpPort: 7474
  httpsPort: 7473
  boltPort: 7687

environment:
  NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
  NEO4J_AUTH: "neo4j/phac@2023"
  NEO4J_server_default__advertised__address: "neo4j"
  NEO4j_server_bolt_advertised_address: ":7687"
  NEO4j_server_http_advertised_address: ":7474"
  NEO4J_server_default__listen__address: "0.0.0.0"
  NEO4j_server_bolt_listen_address: ":7687"
  NEO4j_server_http_listen_address: ":7474"
  NEO4J_server_memory_pagecache_size: "8G"
  NEO4J_server_memory_heap_initial__size: "8G"
  NEO4J_server_memory_heap_max__size: "16G"
  NEO4J_apoc_export_file_enabled: "true"
  NEO4J_apoc_import_file_enabled: "true"
  NEO4J_apoc_import_file_use__neo4j__config: "true"
  NEO4J_dbms_security_procedures_unrestricted: "apoc.*,gds.*"


persistence:
  enabled: true
  size: 10Gi
  mounts:
    import: /import
    data: /data
    logs: /logs
    plugins: /plugins

