apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-browser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-browser
  template:
    metadata:
      labels:
        app: patient-browser
        version: v1
    spec:
      containers:
      - name: patient-browser
        image: northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/patient-browser:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: PT
            value: "{{ .Values.paradire.pt | lower }}"
        
