replicaCount: 1

image:
  repository: nielsdejong/neodash
  tag: 2.2.5

service:
  type: LoadBalancer
  port: 5005
  targetPort: 5005

env:
  ssoEnabled: "false"
  standalone: "true"
  standaloneProtocol: "bolt"
  standaloneHost: "neodash"
  standalonePort: "7687"
  standaloneDatabase: "neo4j"
  standaloneDashboardName: "PT Analytics Platform"
  standaloneDashboardDatabase: "neo4j"
