apiVersion: apps/v1
kind: Deployment
metadata:
  name: acg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acg
  template:
    metadata:
      labels:
        app: acg
        version: v1
    spec:
      enableServiceLinks: false
      serviceAccountName: job-service-account
      initContainers:
      - name: wait-for-kafka-job
        image: bitnami/kubectl
        command: ['sh', '-c']
        args:
        - |
          until kubectl get job cp-kafka-job -o jsonpath='{.status.succeeded}' | grep 1; do
            echo "Waiting for cp-kafka-job to complete..."
            sleep 5
          done
          echo "cp-kafka-job completed"
      containers:
      - name: acg
        image: northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/acg
        imagePullPolicy: Always
        env:
        - name: BROKER_LIST
          value: {{ printf "%s:9092" (include "cp-kafka.cp-kafka-headless.fullname" .)  | quote}}
        - name: SCHEMA_REGISTRY_URL
          value: {{ .Values.schemaRegistry.url | quote }}
        - name: F_BROKER_LIST
          value: {{ printf "%s.phac:9092" (include "cp-kafka.cp-kafka-headless.fullname" .)  | quote}}
        - name: F_SCHEMA_REGISTRY_URL
          value: {{ .Values.schemaRegistry.fUrl | quote }}
        - name: F_SCHEMA_REGISTRY_PORT
          value: "8081"
        - name: PT
          value: {{ .Values.pt | upper | quote }}
