apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hapi-fhir-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hapi-fhir-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hapi-fhir-server
    spec:
      containers:
        - image: "{{ .Values.server.image }}"
          name: hapi-fhir-server
          resources:
            requests:
              memory: "10Gi"
              cpu: "10"
          ports:
            - containerPort: {{ .Values.server.targetPort }}
              protocol: TCP
              name: "container-port"
          resources: {}
          volumeMounts:
            - mountPath: /app/config
              name: hapi-fhir-configmap
      restartPolicy: Always
      volumes:
        - name: hapi-fhir-configmap
          configMap:
            name: hapi-fhir-configmap
status: {}