apiVersion: v1
kind: Service
metadata:
  name: hapi-fhir-db-svc
  labels:
    app: hapi-fhir-db-svc
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.targetPort }}
      name: hapi-fhir-db
  selector:
    app: hapi-fhir-db