apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgresPassword: "{{ default "" .Values.postgresSecret.postgresPassword | b64enc }}"
  postgresUser: "{{ default "" .Values.postgresSecret.postgresUser | b64enc }}"
  postgresDB: "{{ default "" .Values.postgresSecret.postgresDB | b64enc }}"