apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgresPassword: {{ .Values.postgresSecret.postgresPassword }}
  postgresUser: {{ .Values.postgresSecret.postgresUser }}
  postgresDB: {{ .Values.postgresSecret.postgresDB }}
