apiVersion: v1
kind: Secret
metadata:
  name: kafka-ui-secret
type: Opaque
data:
  username: "{{ default "" .Values.kafkaUiSecret.username | b64enc }}"
  password: "{{ default "" .Values.kafkaUiSecret.password | b64enc }}"