server:
  image: "hapiproject/hapi:latest"
  port: 8080
  targetPort: 8080

db:
  image: "postgres"
  volumeMount: "/var/lib/postgresql/data" 
  size: "10Gi"
  port: 5432
  targetPort: 5432
  pgdata: "/var/lib/postgresql/data/random/"

paradire:
  pt: nb

postgresSecret:
  postgresPassword:
  postgresUser:
  postgresDB:
