apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-production
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: luc.belliveau@canada.ca
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - selector: {}
        dns01:
          cloudDNS:
            project: phx-01he5rx4wsv
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json
