apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: simardeep.singh@hc-sc.gc.ca
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - selector: {}
        dns01:
          cloudDNS:
            project: phx-01he5rx4wsv
            hostedZoneName: paradire-alpha-phac-gc-ca
