# Create initially empty secret to contain SSL keys
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cp-kafka-ui.fullname" . }}-ssl
type: kubernetes.io/tls
stringData:
  tls.key: ""
  tls.crt: ""