apiVersion: v1
kind: Secret
metadata:
  name: prometheus-secret
data:
  tls.crt: {{ required "A valid .Values.secret.tlsCrt is required!" .Values.secret.crt }}
  tls.key: {{ required "A valid .Values.secret.tlsKey is required!" .Values.secret.key }}
