apiVersion: apps/v1
kind: Deployment
metadata:
  name: governance-ui
  namespace: governance-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: governance-ui
  template:
    metadata:
      labels:
        app: governance-ui
        version: v1
    spec:
      enableServiceLinks: false
      containers:
      - name: governance-ui
        image: northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/governance-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: BROKER_HOST
          value: cp-kafka-rest.cp-kafka-headless
        - name: BROKER_PORT
          value: "9092"
        - name: NEXTAUTH_SECRET
          value: "1234"
        - name: PT
          value: "ab"
        - name: NEXTAUTH_URL
          value: "http://nowhere"
        - name: HOSTNAME
          value: "0.0.0.0"
        - name: GOVERNANCE_UI_URL
          value: "https://governance.ab.paradire.alpha.phac.gc.ca"
        - name: GOVERNANCE_WS_URL
          value: "wss://governance.ab.paradire.alpha.phac.gc.ca/ws"
      - name: governance-ui-wss
        image: northamerica-northeast1-docker.pkg.dev/phx-01he5rx4wsv/paradire/governance-ui-wss:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: BROKER_HOST
          value: cp-kafka-rest.cp-kafka-headless
        - name: BROKER_PORT
          value: "9092"
        - name: NEXTAUTH_SECRET
          value: "1234"
        - name: PT
          value: "ab"
        - name: NEXTAUTH_URL
          value: "http://nowhere"
        - name: HOSTNAME
          value: "0.0.0.0"
        - name: GOVERNANCE_UI_URL
          value: "https://governance.ab.paradire.alpha.phac.gc.ca"
        - name: GOVERNANCE_WS_URL
          value: "wss://governance.ab.paradire.alpha.phac.gc.ca/ws"